### ISSUE TITLE
Simple and Bundle product configurable options prices inadequate work

### ISSUE THREAD

**Issue by winniepukki** [scandipwa/scandipwa#2761]
**Description**:
The latest ScandiPWA theme features numerous bugs related to Simple and Bundle product types configurable options prices inadequate work. The following task is design to unite all tasks, related to prices to avoid clashes and confusion

_**Simple and Bundle products with customizable options**_
- [ ] Old price doesn't change when adding item for product with customization options if discount is applied to this product #2677
- [ ] Catalog price rule doesn't apply to product options #2666
- [ ] Wrong product price for simple product with required customization if product has a special price #2674

_**Configurable products**_
- [ ] Configurable product price not updating #2582
- [ ] Wrong prices for config products on PLP and PDP #2760

_**Both or yet unknown**_
- [ ] Specific products don't have price on PLP and PDP #2734

_**Require implementation**_
- [ ] Wrong product price for simple product with required customization if product has a special price #2674

**Expected behavior**:
Configurable options prices should be refactored for the adequate work

**Additional context**:
Please ping @winniepukki in the comment upon finding a new bug, related to prices or shipping one fix. Don't change the following list to avoid confusion

**Comment by aleksandrakorolova** [comment]
@winniepukki I found more issues with prices
1. Regular price excl tax is displayed for product with grouped price or special price or catalog price rule - https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/product-x.html
![Screenshot 2021-06-14 at 09 52 34](https://user-images.githubusercontent.com/73526235/121851173-79a7e700-ccf6-11eb-999b-a6dc6afdbac5.png)
**Expected results:**
Regular price incl tax is displayed for product with grouped price 

2. Wrong price incl tax for products with customizable option and bundle product on PDP (price incl tax = price excl price) - https://master.d25kd40decjpue.amplifyapp.com/default/women/cardigan-in-brown.html
![Screenshot 2021-06-14 at 09 57 08](https://user-images.githubusercontent.com/73526235/121851526-e91dd680-ccf6-11eb-9676-08dd0c91f946.png)
**Expected result:**
Price incl tax is displayed (in this case 45EUR)

**Comment by aleksandrakorolova** [comment]
@winniepukki One more issue with price #2052

**Comment by winniepukki** [comment]
@aleksandrakorolova #2052 is assigned to another developer and will remain exempt from the following task list unless negotiated. Please also note the different milestone

**Comment by carinadues** [comment]
@aleksandrakorolova can you please test issues #2736, #1476, and #2582 (which should be solved by PR 2773) and close them if they're solved? :)

**Comment by aleksandrakorolova** [comment]
Found bugs after testing  #2736, #1476, and #2582 :
1. Dropdowns are disabled for products with customization options 
Product: https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/women/tops/test-category/testing-simple.html
![Screenshot 2021-06-22 at 08 26 43](https://user-images.githubusercontent.com/73526235/122868628-de38f680-d333-11eb-81e1-c370401e58dd.png)

2. Price excl tax is displayed for option with percent for bundle product 
Product: https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html
![Screenshot 2021-06-22 at 08 25 13](https://user-images.githubusercontent.com/73526235/122868715-0163a600-d334-11eb-8079-b9b8de1637af.png)

Also, I noticed that my comment was deleted but issue wasn't fixed:
Price excl.tax = incl.tax for product with customization options and bundles products on PDP (Prices are displayed correctly on PLP)
Product: https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/jeans-for-girls.html
![Screenshot 2021-06-22 at 09 41 29](https://user-images.githubusercontent.com/73526235/122876325-0d546580-d33e-11eb-8815-919471c410e0.png)

**Comment by winniepukki** [comment]
Looks like something passed from [the following](https://github.com/scandipwa/scandipwa/pull/2773) PR

**Comment by winniepukki** [comment]
@aleksandrakorolova the bug appeared after [the following](https://github.com/scandipwa/scandipwa/pull/2795) PR

**Comment by tatiana-scandi** [comment]
@winniepukki 
https://github.com/scandipwa/scandipwa/issues/2674
Please, keep in mind this changes before proceeding with more price fixes.

**Comment by aleksandrakorolova** [comment]
@winniepukki I found one more issue - some product (grouped and downloadable products) has negative amount for excl. tax price
![Screenshot 2021-06-28 at 13 40 21](https://user-images.githubusercontent.com/73526235/123624314-14381800-d817-11eb-98c7-3a6cab08e5c5.png)

**Comment by aleksandrakorolova** [comment]
New issues appear after #2674 :
1. Options price is missing for bundle product with dynamic prices
![Screenshot 2021-06-29 at 08 45 28](https://user-images.githubusercontent.com/73526235/123744231-2073b200-d8b7-11eb-840c-6cb88ae7d51a.png)
Products:
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bun.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/bundle-product-with-dynamic.html

2. Bundle product with fixed price has discount on FE and old price = price with Base Currency from Admin panel 

**Steps:**
Open Admin panel -> Stores -> Configuration -> General -> Currency setup
Set Base currency to EUR
Set Default Display Currency to USD
Save
Clear cache
Open bundle product with fixed price

**Actual result:**
![Screenshot 2021-06-29 at 08 53 39](https://user-images.githubusercontent.com/73526235/123744503-89f3c080-d8b7-11eb-83be-f89e0a07b76a.png)

**Products:** 
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/8bunfixed.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/fixed-bundle-jeans.html
